
ΓÄ»ΓÄ»ΓÄ»ΓÄ»ΓÄ»ΓÄ»ΓÄ» Startup Error ΓÄ»ΓÄ»ΓÄ»ΓÄ»ΓÄ»ΓÄ»ΓÄ»ΓÄ»
Error: Failed to load custom Reporter from spec
    at loadCustomReporterModule (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:7705:9)
    at async file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:7723:28
    ... 3 lines matching cause stack trace ...
    at async _createServer (file:///C:/GplusApp_backup/node_modules/vitest/node_modules/vite/dist/node/chunks/config.js:28192:86)
    at async createViteServer (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:6911:17)
    at async createVitest (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:10202:17)
    at async prepareVitest (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:10541:14)
    at async startVitest (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:10488:14) {
  [cause]: Error: Cannot find package 'spec'
      at ViteNodeRunner._fetchModule (file:///C:/GplusApp_backup/node_modules/vite-node/dist/client.mjs:247:19)
      at async ViteNodeRunner.directRequest (file:///C:/GplusApp_backup/node_modules/vite-node/dist/client.mjs:268:44)
      at async ViteNodeRunner.cachedRequest (file:///C:/GplusApp_backup/node_modules/vite-node/dist/client.mjs:189:11)
      at async ViteNodeRunner.executeId (file:///C:/GplusApp_backup/node_modules/vite-node/dist/client.mjs:166:10)
      at async loadCustomReporterModule (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:7703:26)
      at async file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:7723:28
      at async Promise.all (index 0)
      at async Vitest._setServer (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:9341:138)
      at async BasicMinimalPluginContext.handler (file:///C:/GplusApp_backup/node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:10169:6)
      at async _createServer (file:///C:/GplusApp_backup/node_modules/vitest/node_modules/vite/dist/node/chunks/config.js:28192:86) {
    code: 'ERR_MODULE_NOT_FOUND',
    [cause]: Error: Failed to load url spec (resolved id: spec). Does the file exist?
        at loadAndTransform (file:///C:/GplusApp_backup/node_modules/vitest/node_modules/vite/dist/node/chunks/config.js:26050:33) {
      code: 'ERR_LOAD_URL'
    }
  }
}



