2025-08-01 17:09:13,281 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:09:13,404 - gplus_builder - WARNING - Missing localization key 'app_help_message' for language 'en'. Using default/key: 'app_help_message'
2025-08-01 17:09:13,405 - gplus_builder - WARNING - Missing localization key 'lang_option_help' for language 'en'. Using default/key: 'lang_option_help'
2025-08-01 17:09:13,405 - gplus_builder - WARNING - Missing localization key 'general_options_panel' for language 'en'. Using default/key: 'general_options_panel'
2025-08-01 17:09:13,405 - gplus_builder - WARNING - Missing localization key 'debug_option_help' for language 'en'. Using default/key: 'debug_option_help'
2025-08-01 17:09:13,406 - gplus_builder - WARNING - Missing localization key 'general_options_panel' for language 'en'. Using default/key: 'general_options_panel'
2025-08-01 17:09:13,406 - gplus_builder - WARNING - Missing localization key 'cleanup_confirm_help' for language 'en'. Using default/key: 'cleanup_confirm_help'
2025-08-01 17:09:13,407 - gplus_builder - WARNING - Missing localization key 'cleanup_all_temp_help' for language 'en'. Using default/key: 'cleanup_all_temp_help'
2025-08-01 17:09:13,407 - gplus_builder - WARNING - Missing localization key 'project_name_arg_help' for language 'en'. Using default/key: 'project_name_arg_help'
2025-08-01 17:09:13,407 - gplus_builder - WARNING - Missing localization key 'output_dir_option_help' for language 'en'. Using default/key: 'output_dir_option_help'
2025-08-01 17:09:13,408 - gplus_builder - WARNING - Missing localization key 'template_config_option_help' for language 'en'. Using default/key: 'template_config_option_help'
2025-08-01 17:09:13,408 - gplus_builder - WARNING - Missing localization key 'skip_confirmation_option_help' for language 'en'. Using default/key: 'skip_confirmation_option_help'
2025-08-01 17:09:13,409 - gplus_builder - WARNING - Missing localization key 'component_option_help' for language 'en'. Using default/key: 'component_option_help'
2025-08-01 17:09:13,409 - gplus_builder - WARNING - Missing localization key 'feature_option_help' for language 'en'. Using default/key: 'feature_option_help'
2025-08-01 17:09:13,410 - gplus_builder - WARNING - Missing localization key 'value_option_help' for language 'en'. Using default/key: 'value_option_help'
2025-08-01 17:17:59,104 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:20:04,508 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:20:04,551 - gplus_builder - WARNING - Missing localization key 'about_panel_title' for language 'en'. Using default/key: 'about_panel_title'
2025-08-01 17:20:04,553 - gplus_builder - WARNING - Missing localization key 'info_item_column' for language 'en'. Using default/key: 'info_item_column'
2025-08-01 17:20:04,553 - gplus_builder - WARNING - Missing localization key 'info_value_column' for language 'en'. Using default/key: 'info_value_column'
2025-08-01 17:20:04,554 - gplus_builder - WARNING - Missing localization key 'app_name_label' for language 'en'. Using default/key: 'app_name_label'
2025-08-01 17:20:04,554 - gplus_builder - WARNING - Missing localization key 'version_label' for language 'en'. Using default/key: 'version_label'
2025-08-01 17:20:04,555 - gplus_builder - WARNING - Missing localization key 'author_label' for language 'en'. Using default/key: 'author_label'
2025-08-01 17:20:04,555 - gplus_builder - WARNING - Missing localization key 'license_label' for language 'en'. Using default/key: 'license_label'
2025-08-01 17:20:04,556 - gplus_builder - WARNING - Missing localization key 'website_label' for language 'en'. Using default/key: 'website_label'
2025-08-01 17:20:04,557 - gplus_builder - WARNING - Missing localization key 'github_label' for language 'en'. Using default/key: 'github_label'
2025-08-01 17:20:04,558 - gplus_builder - WARNING - Missing localization key 'python_version_label' for language 'en'. Using default/key: 'python_version_label'
2025-08-01 17:20:04,558 - gplus_builder - WARNING - Missing localization key 'os_label' for language 'en'. Using default/key: 'os_label'
2025-08-01 17:20:04,559 - gplus_builder - WARNING - Missing localization key 'current_locale_label' for language 'en'. Using default/key: 'current_locale_label'
2025-08-01 17:20:04,566 - gplus_builder - WARNING - Missing localization key 'config_info_title' for language 'en'. Using default/key: 'config_info_title'
2025-08-01 17:20:04,567 - gplus_builder - WARNING - Missing localization key 'info_item_column' for language 'en'. Using default/key: 'info_item_column'
2025-08-01 17:20:04,568 - gplus_builder - WARNING - Missing localization key 'info_value_column' for language 'en'. Using default/key: 'info_value_column'
2025-08-01 17:20:04,568 - gplus_builder - WARNING - Missing localization key 'log_dir_label' for language 'en'. Using default/key: 'log_dir_label'
2025-08-01 17:20:04,569 - gplus_builder - WARNING - Missing localization key 'cache_dir_label' for language 'en'. Using default/key: 'cache_dir_label'
2025-08-01 17:20:04,570 - gplus_builder - WARNING - Missing localization key 'locale_dir_label' for language 'en'. Using default/key: 'locale_dir_label'
2025-08-01 17:20:04,570 - gplus_builder - WARNING - Missing localization key 'templates_dir_label' for language 'en'. Using default/key: 'templates_dir_label'
2025-08-01 17:20:04,571 - gplus_builder - WARNING - Missing localization key 'default_lang_label' for language 'en'. Using default/key: 'default_lang_label'
2025-08-01 17:20:04,571 - gplus_builder - WARNING - Missing localization key 'log_level_label' for language 'en'. Using default/key: 'log_level_label'
2025-08-01 17:20:04,577 - gplus_builder - WARNING - Missing localization key 'global_features_title' for language 'en'. Using default/key: 'global_features_title'
2025-08-01 17:20:04,585 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 17:20:04,587 - gplus_builder - WARNING - Missing localization key 'template_loading_error' for language 'en'. Using default/key: 'template_loading_error'
2025-08-01 17:20:04,591 - gplus_builder - WARNING - Missing localization key 'resource_limits_title' for language 'en'. Using default/key: 'resource_limits_title'
2025-08-01 17:20:04,592 - gplus_builder - WARNING - Resource limits are not fully supported on this operating system.
2025-08-01 17:20:04,593 - gplus_builder - WARNING - Missing localization key 'resource_limits_unavailable' for language 'en'. Using default/key: 'resource_limits_unavailable'
2025-08-01 17:20:04,595 - gplus_builder - WARNING - Missing localization key 'supported_languages_title' for language 'en'. Using default/key: 'supported_languages_title'
2025-08-01 17:20:04,598 - gplus_builder - WARNING - Missing localization key 'code_column' for language 'en'. Using default/key: 'code_column'
2025-08-01 17:20:04,598 - gplus_builder - WARNING - Missing localization key 'name_column' for language 'en'. Using default/key: 'name_column'
2025-08-01 17:20:04,652 - gplus_builder - WARNING - Missing localization key 'en' for language 'en'. Using default/key: 'English'
2025-08-01 17:21:46,573 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:21:46,608 - gplus_builder - WARNING - Missing localization key 'cleanup_confirmation_prompt' for language 'en'. Using default/key: 'cleanup_confirmation_prompt'
2025-08-01 17:23:41,742 - gplus_builder - WARNING - Missing localization key 'cleaning_up_temp_dirs' for language 'en'. Using default/key: 'cleaning_up_temp_dirs'
2025-08-01 17:23:41,744 - gplus_builder - INFO - cleaning_up_temp_dirs
2025-08-01 17:23:41,750 - gplus_builder - WARNING - Missing localization key 'failed_to_remove_directory' for language 'en'. Using default/key: 'failed_to_remove_directory'
2025-08-01 17:23:41,750 - gplus_builder - ERROR - failed_to_remove_directory
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\cache'
2025-08-01 17:23:41,782 - gplus_builder - WARNING - Missing localization key 'failed_to_remove_directory' for language 'en'. Using default/key: 'failed_to_remove_directory'
2025-08-01 17:23:41,783 - gplus_builder - ERROR - failed_to_remove_directory
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\logs\\gplus_smart_builder_pro.log'
2025-08-01 17:23:41,787 - gplus_builder - WARNING - Missing localization key 'cache_and_logs_cleared' for language 'en'. Using default/key: 'cache_and_logs_cleared'
2025-08-01 17:23:41,788 - gplus_builder - INFO - cache_and_logs_cleared
2025-08-01 17:23:41,789 - gplus_builder - WARNING - Missing localization key 'cleanup_complete' for language 'en'. Using default/key: 'cleanup_complete'
2025-08-01 17:23:41,790 - gplus_builder - INFO - cleanup_complete
2025-08-01 17:24:42,187 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:25:09,742 - gplus_builder - WARNING - Missing localization key 'cleaning_up_temp_dirs' for language 'en'. Using default/key: 'cleaning_up_temp_dirs'
2025-08-01 17:25:09,743 - gplus_builder - INFO - cleaning_up_temp_dirs
2025-08-01 17:25:09,750 - gplus_builder - WARNING - Missing localization key 'failed_to_remove_directory' for language 'en'. Using default/key: 'failed_to_remove_directory'
2025-08-01 17:25:09,751 - gplus_builder - ERROR - failed_to_remove_directory
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\cache'
2025-08-01 17:25:09,757 - gplus_builder - WARNING - Missing localization key 'failed_to_remove_directory' for language 'en'. Using default/key: 'failed_to_remove_directory'
2025-08-01 17:25:09,759 - gplus_builder - ERROR - failed_to_remove_directory
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\logs\\gplus_smart_builder_pro.log'
2025-08-01 17:25:09,764 - gplus_builder - WARNING - Missing localization key 'cache_and_logs_cleared' for language 'en'. Using default/key: 'cache_and_logs_cleared'
2025-08-01 17:25:09,764 - gplus_builder - INFO - cache_and_logs_cleared
2025-08-01 17:25:09,765 - gplus_builder - WARNING - Missing localization key 'cleanup_complete' for language 'en'. Using default/key: 'cleanup_complete'
2025-08-01 17:25:09,766 - gplus_builder - INFO - cleanup_complete
2025-08-01 17:25:44,320 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:26:01,912 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:29:36,212 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:29:36,255 - gplus_builder - WARNING - Missing localization key 'about_panel_title' for language 'en'. Using default/key: 'about_panel_title'
2025-08-01 17:29:36,258 - gplus_builder - WARNING - Missing localization key 'info_item_column' for language 'en'. Using default/key: 'info_item_column'
2025-08-01 17:29:36,259 - gplus_builder - WARNING - Missing localization key 'info_value_column' for language 'en'. Using default/key: 'info_value_column'
2025-08-01 17:29:36,260 - gplus_builder - WARNING - Missing localization key 'app_name_label' for language 'en'. Using default/key: 'app_name_label'
2025-08-01 17:29:36,261 - gplus_builder - WARNING - Missing localization key 'version_label' for language 'en'. Using default/key: 'version_label'
2025-08-01 17:29:36,262 - gplus_builder - WARNING - Missing localization key 'author_label' for language 'en'. Using default/key: 'author_label'
2025-08-01 17:29:36,263 - gplus_builder - WARNING - Missing localization key 'license_label' for language 'en'. Using default/key: 'license_label'
2025-08-01 17:29:36,264 - gplus_builder - WARNING - Missing localization key 'website_label' for language 'en'. Using default/key: 'website_label'
2025-08-01 17:29:36,265 - gplus_builder - WARNING - Missing localization key 'github_label' for language 'en'. Using default/key: 'github_label'
2025-08-01 17:29:36,266 - gplus_builder - WARNING - Missing localization key 'python_version_label' for language 'en'. Using default/key: 'python_version_label'
2025-08-01 17:29:36,268 - gplus_builder - WARNING - Missing localization key 'os_label' for language 'en'. Using default/key: 'os_label'
2025-08-01 17:29:36,269 - gplus_builder - WARNING - Missing localization key 'current_locale_label' for language 'en'. Using default/key: 'current_locale_label'
2025-08-01 17:29:36,277 - gplus_builder - WARNING - Missing localization key 'config_info_title' for language 'en'. Using default/key: 'config_info_title'
2025-08-01 17:29:36,279 - gplus_builder - WARNING - Missing localization key 'info_item_column' for language 'en'. Using default/key: 'info_item_column'
2025-08-01 17:29:36,280 - gplus_builder - WARNING - Missing localization key 'info_value_column' for language 'en'. Using default/key: 'info_value_column'
2025-08-01 17:29:36,281 - gplus_builder - WARNING - Missing localization key 'log_dir_label' for language 'en'. Using default/key: 'log_dir_label'
2025-08-01 17:29:36,282 - gplus_builder - WARNING - Missing localization key 'cache_dir_label' for language 'en'. Using default/key: 'cache_dir_label'
2025-08-01 17:29:36,284 - gplus_builder - WARNING - Missing localization key 'locale_dir_label' for language 'en'. Using default/key: 'locale_dir_label'
2025-08-01 17:29:36,292 - gplus_builder - WARNING - Missing localization key 'templates_dir_label' for language 'en'. Using default/key: 'templates_dir_label'
2025-08-01 17:29:36,294 - gplus_builder - WARNING - Missing localization key 'default_lang_label' for language 'en'. Using default/key: 'default_lang_label'
2025-08-01 17:29:36,321 - gplus_builder - WARNING - Missing localization key 'log_level_label' for language 'en'. Using default/key: 'log_level_label'
2025-08-01 17:29:36,354 - gplus_builder - WARNING - Missing localization key 'global_features_title' for language 'en'. Using default/key: 'global_features_title'
2025-08-01 17:29:36,360 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 17:29:36,367 - gplus_builder - WARNING - Missing localization key 'template_loading_error' for language 'en'. Using default/key: 'template_loading_error'
2025-08-01 17:29:36,369 - gplus_builder - WARNING - Missing localization key 'resource_limits_title' for language 'en'. Using default/key: 'resource_limits_title'
2025-08-01 17:29:36,371 - gplus_builder - WARNING - Resource limits are not fully supported on this operating system.
2025-08-01 17:29:36,372 - gplus_builder - WARNING - Missing localization key 'resource_limits_unavailable' for language 'en'. Using default/key: 'resource_limits_unavailable'
2025-08-01 17:29:36,374 - gplus_builder - WARNING - Missing localization key 'supported_languages_title' for language 'en'. Using default/key: 'supported_languages_title'
2025-08-01 17:29:36,375 - gplus_builder - WARNING - Missing localization key 'code_column' for language 'en'. Using default/key: 'code_column'
2025-08-01 17:29:36,375 - gplus_builder - WARNING - Missing localization key 'name_column' for language 'en'. Using default/key: 'name_column'
2025-08-01 17:29:36,387 - gplus_builder - WARNING - Missing localization key 'en' for language 'en'. Using default/key: 'English'
2025-08-01 17:30:38,412 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:30:38,473 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 17:30:38,478 - gplus_builder - WARNING - Resource limits are not fully supported on this operating system.
2025-08-01 17:32:17,346 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:33:13,555 - gplus_builder - WARNING - Missing localization key 'cleaning_up_temp_dirs' for language 'en'. Using default/key: 'cleaning_up_temp_dirs'
2025-08-01 17:33:13,556 - gplus_builder - INFO - cleaning_up_temp_dirs
2025-08-01 17:33:13,562 - gplus_builder - WARNING - Missing localization key 'failed_to_remove_directory' for language 'en'. Using default/key: 'failed_to_remove_directory'
2025-08-01 17:33:13,563 - gplus_builder - ERROR - failed_to_remove_directory
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\cache'
2025-08-01 17:33:13,568 - gplus_builder - WARNING - Missing localization key 'failed_to_remove_directory' for language 'en'. Using default/key: 'failed_to_remove_directory'
2025-08-01 17:33:13,569 - gplus_builder - ERROR - failed_to_remove_directory
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\logs\\gplus_smart_builder_pro.log'
2025-08-01 17:33:13,573 - gplus_builder - WARNING - Missing localization key 'cache_and_logs_cleared' for language 'en'. Using default/key: 'cache_and_logs_cleared'
2025-08-01 17:33:13,574 - gplus_builder - INFO - cache_and_logs_cleared
2025-08-01 17:33:13,575 - gplus_builder - WARNING - Missing localization key 'cleanup_complete' for language 'en'. Using default/key: 'cleanup_complete'
2025-08-01 17:33:13,576 - gplus_builder - INFO - cleanup_complete
2025-08-01 17:33:19,630 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:34:00,960 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:35:14,624 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:35:17,421 - gplus_builder - INFO - Cleaning up temporary directories...
2025-08-01 17:35:17,427 - gplus_builder - ERROR - Failed to remove directory or file due to permission error.
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\cache'
2025-08-01 17:35:17,433 - gplus_builder - ERROR - Failed to remove directory or file due to permission error.
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 999, in cleanup_temp_dirs
    shutil.rmtree(path)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\logs\\gplus_smart_builder_pro.log'
2025-08-01 17:35:17,437 - gplus_builder - INFO - Cache and logs have been cleared.
2025-08-01 17:35:17,439 - gplus_builder - INFO - Cleanup process is complete.
2025-08-01 17:35:24,644 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:58:07,140 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:59:21,414 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 17:59:21,455 - gplus_builder - WARNING - Missing localization key 'generating_new_project' for language 'en'. Using default/key: 'generating_new_project'
2025-08-01 17:59:21,456 - gplus_builder - INFO - generating_new_project
2025-08-01 17:59:21,462 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 17:59:21,465 - gplus_builder - WARNING - Missing localization key 'loading_project_config' for language 'en'. Using default/key: 'loading_project_config'
2025-08-01 17:59:21,465 - gplus_builder - INFO - loading_project_config
2025-08-01 17:59:21,474 - gplus_builder - CRITICAL - An unexpected error occurred during project generation: 8 validation errors for ProjectStructureConfig
project_type
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
description
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.description
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.template_path
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.output_path
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.description
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.template_path
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.output_path
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 216, in new_project_command
    project_structure = ProjectStructureConfig(**project_config_data)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 8 validation errors for ProjectStructureConfig
project_type
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
description
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.description
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.template_path
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.output_path
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.description
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.template_path
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.output_path
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-08-01 17:59:21,493 - gplus_builder - WARNING - Missing localization key 'project_generation_failed_unexpected' for language 'en'. Using default/key: 'An unexpected error occurred during project generation: {error}'
2025-08-01 17:59:21,503 - gplus_builder - CRITICAL - Unexpected Error in command 'new_project_command': 1
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 216, in new_project_command
    project_structure = ProjectStructureConfig(**project_config_data)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 8 validation errors for ProjectStructureConfig
project_type
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
description
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.description
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.template_path
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.0.output_path
  Field required [type=missing, input_value={'name': 'core', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.description
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.template_path
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
components.1.output_path
  Field required [type=missing, input_value={'name': 'api', 'enabled': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 231, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 534, in new_project_command
    raise typer.Exit(1)
click.exceptions.Exit: 1
2025-08-01 17:59:21,510 - gplus_builder - WARNING - Missing localization key 'unexpected_command_error' for language 'en'. Using default/key: 'unexpected_command_error'
2025-08-01 18:00:52,843 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 18:00:52,886 - gplus_builder - WARNING - Missing localization key 'generating_new_project' for language 'en'. Using default/key: 'generating_new_project'
2025-08-01 18:00:52,887 - gplus_builder - INFO - generating_new_project
2025-08-01 18:00:52,894 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 18:00:52,897 - gplus_builder - WARNING - Missing localization key 'loading_project_config' for language 'en'. Using default/key: 'loading_project_config'
2025-08-01 18:00:52,898 - gplus_builder - INFO - loading_project_config
2025-08-01 18:00:52,909 - gplus_builder - CRITICAL - An unexpected error occurred during project generation: 2 validation errors for ProjectStructureConfig
project_type
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
description
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 216, in new_project_command
    project_structure = ProjectStructureConfig(**project_config_data)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ProjectStructureConfig
project_type
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
description
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-08-01 18:00:52,919 - gplus_builder - WARNING - Missing localization key 'project_generation_failed_unexpected' for language 'en'. Using default/key: 'An unexpected error occurred during project generation: {error}'
2025-08-01 18:00:52,923 - gplus_builder - CRITICAL - Unexpected Error in command 'new_project_command': 1
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 216, in new_project_command
    project_structure = ProjectStructureConfig(**project_config_data)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ProjectStructureConfig
project_type
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
description
  Field required [type=missing, input_value={'project': {'name': 'GPl...ocs', 'enabled': True}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 231, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 534, in new_project_command
    raise typer.Exit(1)
click.exceptions.Exit: 1
2025-08-01 18:00:52,928 - gplus_builder - WARNING - Missing localization key 'unexpected_command_error' for language 'en'. Using default/key: 'unexpected_command_error'
2025-08-01 18:01:51,376 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 18:01:51,416 - gplus_builder - WARNING - Missing localization key 'generating_new_project' for language 'en'. Using default/key: 'generating_new_project'
2025-08-01 18:01:51,417 - gplus_builder - INFO - generating_new_project
2025-08-01 18:01:51,424 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 18:01:51,427 - gplus_builder - WARNING - Missing localization key 'loading_project_config' for language 'en'. Using default/key: 'loading_project_config'
2025-08-01 18:01:51,428 - gplus_builder - INFO - loading_project_config
2025-08-01 18:01:51,440 - gplus_builder - WARNING - Missing localization key 'project_config_loaded' for language 'en'. Using default/key: 'project_config_loaded'
2025-08-01 18:01:51,441 - gplus_builder - INFO - project_config_loaded
2025-08-01 18:01:51,443 - gplus_builder - WARNING - Missing localization key 'collecting_user_input' for language 'en'. Using default/key: 'collecting_user_input'
2025-08-01 18:01:51,444 - gplus_builder - INFO - collecting_user_input
2025-08-01 18:01:51,446 - gplus_builder - WARNING - Missing localization key 'select_components_title' for language 'en'. Using default/key: 'select_components_title'
2025-08-01 18:04:59,185 - gplus_builder - CRITICAL - An unexpected error occurred during project generation: Object of type Config is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 344, in new_project_command
    log_debug(f"Jinja2 Context: {json.dumps(global_context, indent=2)}")
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Config is not JSON serializable
2025-08-01 18:04:59,236 - gplus_builder - WARNING - Missing localization key 'project_generation_failed_unexpected' for language 'en'. Using default/key: 'An unexpected error occurred during project generation: {error}'
2025-08-01 18:04:59,237 - gplus_builder - CRITICAL - Unexpected Error in command 'new_project_command': 1
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 344, in new_project_command
    log_debug(f"Jinja2 Context: {json.dumps(global_context, indent=2)}")
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Config is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 231, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 534, in new_project_command
    raise typer.Exit(1)
click.exceptions.Exit: 1
2025-08-01 18:04:59,242 - gplus_builder - WARNING - Missing localization key 'unexpected_command_error' for language 'en'. Using default/key: 'unexpected_command_error'
2025-08-01 18:06:49,827 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 18:06:49,871 - gplus_builder - INFO - Generating new project...
2025-08-01 18:06:49,879 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 18:06:49,882 - gplus_builder - INFO - Loading project configuration...
2025-08-01 18:06:49,893 - gplus_builder - INFO - Project configuration loaded successfully.
2025-08-01 18:06:49,895 - gplus_builder - INFO - Collecting user input...
2025-08-01 18:06:53,407 - gplus_builder - WARNING - Missing localization key 'project_summary_title' for language 'en'. Using default/key: 'project_summary_title'
2025-08-01 18:06:53,415 - gplus_builder - WARNING - Missing localization key 'proceed_with_generation_prompt' for language 'en'. Using default/key: 'proceed_with_generation_prompt'
2025-08-01 18:11:18,293 - gplus_builder - WARNING - Missing localization key 'creating_project_root' for language 'en'. Using default/key: 'creating_project_root'
2025-08-01 18:11:18,294 - gplus_builder - INFO - creating_project_root
2025-08-01 18:11:18,297 - gplus_builder - WARNING - Missing localization key 'project_root_created' for language 'en'. Using default/key: 'project_root_created'
2025-08-01 18:11:18,297 - gplus_builder - INFO - project_root_created
2025-08-01 18:11:18,299 - gplus_builder - WARNING - Missing localization key 'root_env_template' for language 'en'. Using default/key: 'root_env_template'
2025-08-01 18:11:18,301 - gplus_builder - WARNING - Missing localization key 'root_env_created' for language 'en'. Using default/key: 'root_env_created'
2025-08-01 18:11:18,302 - gplus_builder - INFO - root_env_created
2025-08-01 18:11:18,304 - gplus_builder - WARNING - Missing localization key 'root_gitignore_template' for language 'en'. Using default/key: 'root_gitignore_template'
2025-08-01 18:11:18,306 - gplus_builder - WARNING - Missing localization key 'root_gitignore_created' for language 'en'. Using default/key: 'root_gitignore_created'
2025-08-01 18:11:18,307 - gplus_builder - INFO - root_gitignore_created
2025-08-01 18:11:18,313 - gplus_builder - WARNING - Missing localization key 'generating_components_progress' for language 'en'. Using default/key: 'generating_components_progress'
2025-08-01 18:11:18,320 - gplus_builder - WARNING - Missing localization key 'project_generation_complete' for language 'en'. Using default/key: 'project_generation_complete'
2025-08-01 18:11:18,321 - gplus_builder - INFO - project_generation_complete
2025-08-01 18:11:18,322 - gplus_builder - WARNING - Missing localization key 'no_post_gen_commands' for language 'en'. Using default/key: 'no_post_gen_commands'
2025-08-01 18:11:18,323 - gplus_builder - INFO - no_post_gen_commands
2025-08-01 18:11:18,324 - gplus_builder - WARNING - Missing localization key 'next_steps_title' for language 'en'. Using default/key: 'next_steps_title'
2025-08-01 18:11:18,325 - gplus_builder - WARNING - Missing localization key 'next_steps_cd' for language 'en'. Using default/key: 'next_steps_cd'
2025-08-01 18:11:18,326 - gplus_builder - WARNING - Missing localization key 'next_steps_install_deps' for language 'en'. Using default/key: 'next_steps_install_deps'
2025-08-01 18:11:18,329 - gplus_builder - WARNING - Missing localization key 'next_steps_run_app' for language 'en'. Using default/key: 'next_steps_run_app'
2025-08-01 18:11:18,330 - gplus_builder - WARNING - Missing localization key 'next_steps_read_docs' for language 'en'. Using default/key: 'next_steps_read_docs'
2025-08-01 18:11:35,159 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 18:11:35,196 - gplus_builder - INFO - Generating new project...
2025-08-01 18:11:35,204 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 18:11:35,207 - gplus_builder - WARNING - Missing localization key 'project_dir_exists_prompt' for language 'en'. Using default/key: 'project_dir_exists_prompt'
2025-08-01 18:11:39,177 - gplus_builder - CRITICAL - Unexpected Error in command 'new_project_command': [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\gplus-smart-builder-pro'
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 231, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 196, in new_project_command
    shutil.rmtree(project_root)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\gplus-smart-builder-pro'
2025-08-01 18:11:39,184 - gplus_builder - WARNING - Missing localization key 'unexpected_command_error' for language 'en'. Using default/key: 'unexpected_command_error'
2025-08-01 18:13:14,847 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 18:13:14,890 - gplus_builder - INFO - Generating new project...
2025-08-01 18:13:14,899 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 18:13:14,903 - gplus_builder - WARNING - Missing localization key 'project_dir_exists_prompt' for language 'en'. Using default/key: 'project_dir_exists_prompt'
2025-08-01 18:13:18,226 - gplus_builder - CRITICAL - Unexpected Error in command 'new_project_command': [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\gplus-smart-builder-pro'
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\gplus_core.py", line 231, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\app.py", line 196, in new_project_command
    shutil.rmtree(project_root)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Moamen Ahmed\\OneDrive\\Desktop\\GplusApp\\gplus-smart-builder-pro'
2025-08-01 18:13:18,231 - gplus_builder - WARNING - Missing localization key 'unexpected_command_error' for language 'en'. Using default/key: 'unexpected_command_error'
2025-08-01 18:15:20,759 - gplus_builder - INFO - Logging level set to INFO
2025-08-01 18:15:20,803 - gplus_builder - INFO - Generating new project...
2025-08-01 18:15:20,809 - gplus_builder - INFO - TemplateManager initialized with templates base path: C:\Users\Moamen Ahmed\OneDrive\Desktop\GplusApp\templates
2025-08-01 18:15:20,812 - gplus_builder - INFO - Loading project configuration...
2025-08-01 18:15:20,822 - gplus_builder - INFO - Project configuration loaded successfully.
2025-08-01 18:15:20,824 - gplus_builder - INFO - Collecting user input...
2025-08-01 18:16:40,976 - gplus_builder - WARNING - Missing localization key 'creating_project_root' for language 'en'. Using default/key: 'creating_project_root'
2025-08-01 18:16:40,976 - gplus_builder - INFO - creating_project_root
2025-08-01 18:16:40,985 - gplus_builder - WARNING - Missing localization key 'project_root_created' for language 'en'. Using default/key: 'project_root_created'
2025-08-01 18:16:40,986 - gplus_builder - INFO - project_root_created
2025-08-01 18:16:40,989 - gplus_builder - WARNING - Missing localization key 'root_env_template' for language 'en'. Using default/key: 'root_env_template'
2025-08-01 18:16:40,991 - gplus_builder - WARNING - Missing localization key 'root_env_created' for language 'en'. Using default/key: 'root_env_created'
2025-08-01 18:16:40,993 - gplus_builder - INFO - root_env_created
2025-08-01 18:16:40,994 - gplus_builder - WARNING - Missing localization key 'root_gitignore_template' for language 'en'. Using default/key: 'root_gitignore_template'
2025-08-01 18:16:40,996 - gplus_builder - WARNING - Missing localization key 'root_gitignore_created' for language 'en'. Using default/key: 'root_gitignore_created'
2025-08-01 18:16:40,996 - gplus_builder - INFO - root_gitignore_created
2025-08-01 18:16:41,005 - gplus_builder - WARNING - Missing localization key 'generating_components_progress' for language 'en'. Using default/key: 'generating_components_progress'
2025-08-01 18:16:41,009 - gplus_builder - WARNING - Missing localization key 'generating_component' for language 'en'. Using default/key: 'generating_component'
2025-08-01 18:16:41,010 - gplus_builder - INFO - generating_component
2025-08-01 18:16:41,026 - gplus_builder - WARNING - Missing localization key 'component_generated_success' for language 'en'. Using default/key: 'component_generated_success'
2025-08-01 18:16:41,027 - gplus_builder - INFO - component_generated_success
2025-08-01 18:16:41,031 - gplus_builder - WARNING - Missing localization key 'generating_component' for language 'en'. Using default/key: 'generating_component'
2025-08-01 18:16:41,032 - gplus_builder - INFO - generating_component
2025-08-01 18:16:41,042 - gplus_builder - WARNING - Missing localization key 'component_generated_success' for language 'en'. Using default/key: 'component_generated_success'
2025-08-01 18:16:41,042 - gplus_builder - INFO - component_generated_success
2025-08-01 18:16:41,067 - gplus_builder - WARNING - Missing localization key 'project_generation_complete' for language 'en'. Using default/key: 'project_generation_complete'
2025-08-01 18:16:41,067 - gplus_builder - INFO - project_generation_complete
2025-08-01 18:16:41,069 - gplus_builder - WARNING - Missing localization key 'no_post_gen_commands' for language 'en'. Using default/key: 'no_post_gen_commands'
2025-08-01 18:16:41,069 - gplus_builder - INFO - no_post_gen_commands
2025-08-01 18:16:41,071 - gplus_builder - WARNING - Missing localization key 'next_steps_title' for language 'en'. Using default/key: 'next_steps_title'
2025-08-01 18:16:41,072 - gplus_builder - WARNING - Missing localization key 'next_steps_cd' for language 'en'. Using default/key: 'next_steps_cd'
2025-08-01 18:16:41,074 - gplus_builder - WARNING - Missing localization key 'next_steps_install_deps' for language 'en'. Using default/key: 'next_steps_install_deps'
2025-08-01 18:16:41,075 - gplus_builder - WARNING - Missing localization key 'next_steps_run_app' for language 'en'. Using default/key: 'next_steps_run_app'
2025-08-01 18:16:41,076 - gplus_builder - WARNING - Missing localization key 'next_steps_read_docs' for language 'en'. Using default/key: 'next_steps_read_docs'
2025-10-09 01:24:07,095 - gplus_builder - INFO - Logging level set to INFO
